services:
  cloudmusic:
    image: ghcr.io/lillinlin/cloudmusic-manager:latest
    container_name: cloudmusic
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - ./data:/app/data
